### ISSUE TITLE
Encode gives diferent deck

### ISSUE THREAD

**Issue by Dinidiniz** [Rafalonso/LoRDeckCodesPython#3] opened 2020-05-14 20:23 UTC
I have the following deck:

lor_cards = ['3:01NX020', '3:01NX012', '3:01NX040', '3:01NX015', '3:01NX030', '3:01PZ054', '3:01NX037', '3:02NX004', '3:01PZ017', '1:01NX047', '3:01PZ052', '3:02NX003', '3:01PZ039', '3:01NX002']
deck_lor_code = LoRDeck(lor_cards).encode()

It gives me an encode of a diferent deck (with 49 cards)

**Comment by Rafalonso** [comment] 2020-05-14 21:42
Hello @Dinidiniz
Thank you for bringing this to my attention, I have reproduced the bug and will be launching a fix tomorrow.

**Comment by Dinidiniz** [comment] 2020-05-15 04:04
Thanks for the great work

**Comment by Rafalonso** [comment] 2020-05-15 10:40
@Dinidiniz 
Issue has been fixed, please update to version 1.1.0, if the issue is fixed please close this issue, if you experience any other issue or have a feature suggestion please open another one. Again, thank you for reporting.

**Closed** 2020-05-15 16:34 UTC
Labels: bug
